version: "3.8"
services:
    mongon:
        container_name: mongon
        restart: on-failure
        build:
            dockerfile: docker/api/Dockerfile
            context: .
            target: dev
        volumes:
            - .:/application:cached
            - go-mod-cache:/go/pkg/mod
        environment:
            - GO111MODULE=on
        ports:
            - 8080:8080

volumes:
    go-mod-cache:

networks:
    default:
        name: mongonn
        external: true